services:
  victor:
    image: ironedge/victor:latest
    restart: unless-stopped
    ports:
      - '8125:8125/udp'
    volumes:
      - "${PWD}/config/config-local.yaml:/app/config/config.yaml"
  telegraf:
    image: telegraf:1.31.3
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/docker/telegraf/config.toml:/etc/telegraf/telegraf.conf"
  grafana:
    image: grafana/grafana:11.5.0
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - "${PWD}/docker/grafana/provisioning:/etc/grafana/provisioning"
      - "${PWD}/docker/grafana/config:/etc/grafana/my-config"
      - "${PWD}/docker/grafana/dashboards:/var/lib/grafana/dashboards"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/my-config/custom.ini
  influxdb:
    image: influxdb:1.11.8
    restart: unless-stopped
    ports:
      - '8086:8086'