metrics-addr: ":8125"
backends:
  - statsdaemon
statsdaemon:
  address: telegraf:8125
  rate-limit:
    enabled: true
    default-limit: 1000
    clear-after-duration: 1h
    limit-by-metric-name:
      test.metrics.inc.1: 500
      test.metrics.timing.1: 250

