[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"

[[inputs.statsd]]
  protocol = "udp"
  service_address = ":8125"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "test"

